runtime: nodejs22

env_variables:
  WEBHOOK_VERIFY_TOKEN: "NGROK"
  GRAPH_API_TOKEN: "EAAGXfnDTLvcBO8wXUPnpqmgMb3ISWcdycOhjwDd6Pm3CWrBZA1rMJM7ZBTKa397HeBLKl9OGPO8u9PVaPRtyWcEwbQhidmgpgTYdotFxivufZBh9kneWHIlKZAqaxss6jLJPpyoMrh4hXZBhvUzZAmIX3zoAGvtpOM6NMCLXZCNtEMyt7ZAAKv7bczQxdXFgCUszBAZDZD"
  BUSINESS_PHONE_NUMBER_ID: "282470614960295"
  FIREBASE_TYPE: "service_account"
  FIREBASE_PROJECT_ID: "natkern-booking"
  FIREBASE_PRIVATE_KEY_ID: "5a6c41dd17f3ac8fcbb3461ef1d1db1b222bf6f1"
  FIREBASE_CLIENT_EMAIL: "firebase-adminsdk-s2f2a@natkern-booking.iam.gserviceaccount.com"
  FIREBASE_CLIENT_ID: "104774771059636750137"
  FIREBASE_AUTH_URI: "https://accounts.google.com/o/oauth2/auth"
  FIREBASE_TOKEN_URI: "https://oauth2.googleapis.com/token"
  FIREBASE_AUTH_PROVIDER_X509_CERT_URL: "https://www.googleapis.com/oauth2/v1/certs"
  FIREBASE_CLIENT_X509_CERT_URL: "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-s2f2a%40natkern-booking.iam.gserviceaccount.com"
  UNIVERSE_DOMAIN: "googleapis.com"
  FIREBASE_DATABASE_URL: "https://natkern-booking-default-rtdb.firebaseio.com/"